name: brazil_consumer_credit_risk
version: "0.1.0"
config-version: 2
profile: brazil_consumer_credit_risk

model-paths: ["models"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  brazil_consumer_credit_risk:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
